# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffdd1e10e7e6a604a8671be1dbb719cd9b44d389ac3a933138eb0775369c1389e90fadfed90d814acb31444aba46c5c3c1ad28ee362a0278291c5e5c8cfa534a

test:
  secret_key_base: f178ded04c93496f407453c91cbb4b68291618a119fb85b4005e59be114abf2062a322153b26a5a806e07690940c23c36a300a26d25357c5360c886ae27b8ef5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
